jobs:
- job: Build
  pool:
    vmImage: $(vmImage)
    
  steps:    
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - task: DotNetCoreCLI@2
      name: 'RestoreNuget'
      inputs:
        command: 'restore'
        projects: '**/*$(projectName).csproj'
        feedsToUse: 'config'
        nugetConfigPath: 'nuget.config'

    - task: DotNetCoreCLI@2
      name: Build
      inputs:
        command: 'build'
        projects: '**/*$(projectName).csproj'
        arguments: '--output $(Build.ArtifactStagingDirectory) --configuration Release'

    - task: DotNetCoreCLI@2
      name: Tests
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - publish: $(Build.ArtifactStagingDirectory)/**/*.*
      artifact: $(artifactName)