# only trigger build through main or release branch
trigger:
- main
- release/*

name: $(MajorVersion).$(MinorVersion).$(Date:yy)$(DayOfYear)$(Rev:.r) 

variables:
  vmImage: 'ubuntu-latest'
  projectName: 'Southport.Messaging.Phone.Twilio'

#------------------------Build DEV------------------------------------------
stages:
- stage: 'BuildDev'
  displayName: 'Build - Dev'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  variables:
    buildConfiguration: 'Release'
    artifactName: 'dev'
  jobs:
  - template: build.yml

#------------------------Build PROD------------------------------------------
- stage: 'BuildProd'
  displayName: 'Build - Prod'
  dependsOn: []
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
  variables:
    buildConfiguration: 'Release'
    artifactName: 'prod'
  jobs:
  - template: build.yml


#------------------------Deploy PROD------------------------------------------
- stage: 'DeployReleaseProd'
  displayName: 'Deploy to prod (release)'
  dependsOn: 'BuildProd'
  condition: succeeded()
  variables:
    environment: 'nuget-publish'
    artifact: prod
    downloadDirectory: 'prod'
    nuGetFeedType: 'external'
  jobs:
  - template: deploy.yml
