# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
stages:
- stage: Build
  jobs:
  - job:
    name: Build

    steps:    

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '5.8.0'
        checkLatest: true

    - task: DotNetCoreCLI@2
      name: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--output $(Build.ArtifactStagingDirectory) --configuration Release'

  - job:
    name: Tests
    steps:

    - task: DotNetCoreCLI@2
      name: Tests
      inputs:
        command: 'test'
        projects: '**/*Test.csproj'
        arguments: '--configuration $(BuildConfiguration)'

  - job:
  name: SaveArtifacts
  steps:

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: Southport.Azure.Functions.Extensions
- stage: Deplyment
  jobs:
  - job:
    name: Deplyment
    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget.org'
